---
title: "HW 2, CS 625, Fall 2022"
author: "Jarrold Fowler"
date: Sep 18, 2022
output: rmarkdown::github_document
---
### Part 2. Analyze Cleaned Data

Use the cleaned data to answer the following questions in your report (and explain how you arrived at the answers):
1. How many types (kinds) of pets are there?

2. How many dogs? 1,122

3. How many breeds of dogs? 324

4. What's the most popular dog breed? Golden Retreiver

5. What's the age range of the dogs? 1 month - 20 years

6. What's the age range of the guinea pigs? ### I removed the category listing for guinea pigs because the options were cat, dog, fish, other ###

7. What is the oldest pet? A cat is 24 and their name is Bruce Springsteen

8. Which are more popular, betta fish or goldfish? How many of each? Based on the "breed" column Beta has a count of 11 and Goldfish has a count of 5

9. What's the most popular everyday name for a cat? Kitty

10. What's the most popular full name for a dog? Bella & Sadie

## References

*Every report must list the references that you consulted while completing the assignment. If you consulted a webpage, you must include the URL.*

* Insert Reference 1, [https://github.com/jgolbeck/petnames](Goldfish raw data set for Homework 2)
* Insert Reference 2, 
* Insert Reference 3, 
